export const PHOTO_ALBUM_INIT = "PHOTO_ALBUM_INIT";
export const PHOTO_ALBUM_START = "PHOTO_ALBUM_START";
export const PHOTO_ALBUM_SUCCESS = "PHOTO_ALBUM_SUCCESS";
export const PHOTO_ALBUM_FAIL = "PHOTO_ALBUM_FAIL";

export const PHOTO_ALBUM_EDIT = "PHOTO_ALBUM_EDIT";
export const PHOTO_ALBUM_REMOVE = "PHOTO_ALBUM_REMOVE";
export const PHOTO_ALBUM_ADD = "PHOTO_ALBUM_ADD";
